---
title: About
author: Richard Lent
date: '2017-04-26'
slug: about
categories: []
tags: []
description: 'About this site and me'
draft: no
topics: []
---
## This site

. . . is written, built, and maintained in [RStudio](https://www.rstudio.com) using the [R](https://www.r-project.org) [blogdown](https://github.com/rstudio/blogdown) package and the [Hugo](https://gohugo.io) static website generator. See [Making a Website Using Blogdown, Hugo, and GitHub](https://proquestionasker.github.io/blog/Making_Site). 

Everything is open-source, plain-text, future-proof, platform-independent, all-natural, and various other things of this nature.

The [emoticon](http://mashable.com/2014/05/23/fun-text-emoticons/#N4_ti1BAhuqw) at the top of the sidebar is [Cthulhu](https://en.wikipedia.org/wiki/Cthulhu), from [H. P. Lovecraft](https://en.wikipedia.org/wiki/H._P._Lovecraft)'s short story [The Call of Cthulhu](http://www.hplovecraft.com/writings/texts/fiction/cc.aspx). 

## Me

Richard A. Lent, Ph.D.
    
Educational Technology Specialist<br>
Information Technology Services<br>
[College of the Holy Cross](http://www.holycross.edu/)<br>
1 College Street<br>
Worcester, Massachusetts USA 01610<br>
[rlent@holycross.edu](mailto:rlent@holycross.edu)

    
EDUCATION<br>
Ph.D [State University of New York at Stony Brook](http://www.stonybrook.edu/) (Ecology and Evolution)<br>
M. S. [University of Vermont](http://www.uvm.edu) (Wildlife and Fisheries Biology)<br>
B. S. [University of Massachusetts at Amherst](http://www.umass.edu) (Natural Resource Studies)<br>
Unix System/C/C++ Programming Certificate, [Worcester Polytechnic Institute](http://www.wpi.edu/)<br>
Data Science Specialization, Johns Hopkins University and [Coursera](https://www.coursera.org/specializations/jhu-data-science) (in progress)<br>
    
POSITIONS<br>
Research Assistant, Carr Research Laboratory, Inc., Wellesley, Massachusetts<br>
Scientist, GCA/Technology Division, Bedford, Massachusetts<br>
Wildlife Biologist, Environmental Research and Technology, Inc., Concord, Massachusetts<br>
Research Assistant, Manomet Bird Observatory, Manomet, Massachusetts<br>
Cornell University Laboratory of Ornithology, Seatuck Research Program; Seatuck Foundation:

* Staff Biologist
* Assistant Director
* Acting Executive Director
* Associate Director of Research

Visiting Assistant Professor of Biology, Amherst College<br>
Adjunct Assistant Professor of Biology, Amherst College.<br>
Data Manager/Ecologist, Harvard University, Harvard Forest<br>
Present position: Educational Technology Specialist, College of the Holy Cross<br>
    
PROFESSIONAL CERTIFICATION<br>
Certified Wildlife Biologist (The Wildlife Society)<br>
Xi Sigma Pi (National Forestry Honor Society, Alpha Omicron Chapter)<br>
    
PROFESSIONAL ORGANIZATIONS<br>
The Wildlife Society<br>
Ecological Society of America<br>
Association of Field Ornithologists<br>
Lepidopterists’ Society<br>
Northeast Arc User's Group<br>









