---
title: Richard A. Lent, Ph.D 
author: Richard Lent
date: '2017-05-04'
slug: publications
categories: []
tags: []
description: Selected Publications
draft: yes
topics: []
---

Brokaw, N. V. L., and **R. A. Lent**. 1999. Vertical diversity. In Maintaining Biodiversity In Forest Ecosystems, M. L. Hunter, Jr., editor. Cambridge University Press.

**Lent, R. A.**, T. S. Litwin, R. P. Cook, J. Bourque, R. Bourque, and J. T. Tanacredi. 1998. Grassland bird habitat restoration at Floyd Bennett Field, Brooklyn, New York: Research and Management. In Grasslands of northeastern North America: Ecology and conservation of native and agricultural landscapes. P. Vickery, ed. Massachusetts Audubon Society, Lincoln, Massachusetts.

**Lent, R. A.**, and D. E. Capen. 1995. Effects of small-scale habitat disturbance on the ecology of breeding birds in a Vermont (USA) hardwood forest. Ecography 18:97-108. [PDF](/pdf/Lent_and_Capen_1995.pdf)

**Lent, R. A.** 1992. Variation in Gray Catbird nest morphology. Journal of Field Ornithology 63(4):411-419. [PDF](/pdf/Lent_1992.pdf)

**Lent, R. A. 1988**. American Oystercatcher. Pages 152-153. In, The Atlas Of Breeding Birds In New York State. R. R. Andrle and J. R. Carroll, Eds. Cornell University Press,
Ithaca, NY.

Brush, T., **R. A. Lent**, T. Hruby, B. A. Harrington, R. M. Marshall, and W. G. Montgomery. 1986. Habitat use by salt marsh birds and response to open marsh water management. Colonial Waterbirds 9:189-195. [PDF](/pdf/Brush_Lent_Hruby_et_al_1986.pdf)

Hruby, T., W. Montgomery, **R. A. Lent**, and N. Dobson. 1985. Open marsh water management in Massachusetts: adapting the technique to local conditions and its impact on mosquito larvae during the first season. Journal of the American Mosquito Control Association 1(1):85-88. [PDF](/pdf/JAMCA_V01_N1_P085-088.pdf)


