---
title: Habitat structure and phenotypic variation in the invading butterfly Coenonympha tullia
author: Richard Lent
date: 2017-05-04T11:18:00-04:00
slug: habitat-structure-and-phenotypic-variation-in-the-invading-butterfly-coenonympha-tullia
categories: []
tags: [reproducible research, butterflies, Lepidoptera]
description: Reproducible research using R and RStudio
draft: yes
topics: [R, R Notebooks, Ecology]
---

The R Notebook [Habitat structure and phenotypic variation in the invading butterfly *Coenonympha tullia*](/rnotebooks/sites.nb.html) is a mockup of a scientific paper (although the field data are real) to illustrate the use of [R Notebooks](http://rmarkdown.rstudio.com/r_notebooks.html) as a means of creating [reproducible research](https://www.crcpress.com/Reproducible-Research-with-R-and-R-Studio-Second-Edition/Gandrud/p/book/9781498715379). The objective is to produce publication-quality output, in HTML, PDF, and Microsoft Word formats, with text, literature citations, a formatted bibliography, statistical analyses, tables, and graphics, all from one, plain-text R Notebook. It illustrates the basic components for creating reproducible research using the tools available in [R](https://www.r-project.org) and [RStudio](https://www.rstudio.com).

Click [here](/rnotebooks/sites.nb.html) to read the notebook.

See also [RStudio as a Research and Writing Platform](/post/rstudio-as-a-research-and-writing-platform/).
